# Generated by Django 2.2.1 on 2019-05-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
